# Generated by Django 2.2.12 on 2020-06-16 09:11

from django.db import migrations


def forwards(apps, schema):
    Teacher = apps.get_model('teachers', 'Teacher')

    def full_name(instance):
        return f"{instance.first_name} {instance.last_name}"

    def info(instance):
        return f'{instance.id} {instance.first_name} {instance.last_name} {instance.age} '

    for teacher in Teacher.objects.all().only('first_name').iterator():
        teacher.first_name = teacher.first_name.capitalize()
        teacher.save(update_fields=['first_name'])

    for teacher in Teacher.objects.all().only('last_name').iterator():
        teacher.last_name = teacher.last_name.capitalize()
        teacher.save(update_fields=['last_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200508_1831'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
