# Generated by Django 2.2.12 on 2020-05-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=64)),
                ('course_name', models.CharField(max_length=64)),
                ('number_of_students', models.PositiveIntegerField()),
            ],
        ),
    ]
